const properties = [
  'http://kulturarvsdata.se/ksamsok#abandonee',
  'http://kulturarvsdata.se/ksamsok#actorActress',
  'http://kulturarvsdata.se/ksamsok#alpha2',
  'http://kulturarvsdata.se/ksamsok#alpha3',
  'http://kulturarvsdata.se/ksamsok#architect',
  'http://kulturarvsdata.se/ksamsok#archiveContributor',
  'http://kulturarvsdata.se/ksamsok#artist',
  'http://kulturarvsdata.se/ksamsok#author',
  'http://kulturarvsdata.se/ksamsok#buildDate',
  'http://kulturarvsdata.se/ksamsok#builder',
  'http://kulturarvsdata.se/ksamsok#buyer',
  'http://kulturarvsdata.se/ksamsok#byline',
  'http://kulturarvsdata.se/ksamsok#cadastralUnit',
  'http://kulturarvsdata.se/ksamsok#carpenter',
  'http://kulturarvsdata.se/ksamsok#client',
  'http://kulturarvsdata.se/ksamsok#collection',
  'http://kulturarvsdata.se/ksamsok#composer',
  'http://kulturarvsdata.se/ksamsok#conservator',
  'http://kulturarvsdata.se/ksamsok#constructionClient',
  'http://kulturarvsdata.se/ksamsok#containsInformationAbout',
  'http://kulturarvsdata.se/ksamsok#containsObject',
  'http://kulturarvsdata.se/ksamsok#contextLabel',
  'http://kulturarvsdata.se/ksamsok#continentName',
  'http://kulturarvsdata.se/ksamsok#coordinates',
  'http://kulturarvsdata.se/ksamsok#copyright',
  'http://kulturarvsdata.se/ksamsok#countryName',
  'http://kulturarvsdata.se/ksamsok#countyName',
  'http://kulturarvsdata.se/ksamsok#createdDate',
  'http://kulturarvsdata.se/ksamsok#depositor',
  'http://kulturarvsdata.se/ksamsok#desc',
  'http://kulturarvsdata.se/ksamsok#description',
  'http://kulturarvsdata.se/ksamsok#designEngineer',
  'http://kulturarvsdata.se/ksamsok#designer',
  'http://kulturarvsdata.se/ksamsok#director',
  'http://kulturarvsdata.se/ksamsok#donor',
  'http://kulturarvsdata.se/ksamsok#employer',
  'http://kulturarvsdata.se/ksamsok#engraver',
  'http://kulturarvsdata.se/ksamsok#eventAuth',
  'http://kulturarvsdata.se/ksamsok#eventName',
  'http://kulturarvsdata.se/ksamsok#examinator',
  'http://kulturarvsdata.se/ksamsok#excavator',
  'http://kulturarvsdata.se/ksamsok#finder',
  'http://kulturarvsdata.se/ksamsok#firstName',
  'http://kulturarvsdata.se/ksamsok#organization',
  'http://kulturarvsdata.se/ksamsok#fromPeriodId',
  'http://kulturarvsdata.se/ksamsok#fromPeriodName',
  'http://kulturarvsdata.se/ksamsok#fromTime',
  'http://kulturarvsdata.se/ksamsok#gender',
  'http://kulturarvsdata.se/ksamsok#generalAgent',
  'http://kulturarvsdata.se/ksamsok#hasBeenUsedIn',
  'http://kulturarvsdata.se/ksamsok#hasChild',
  'http://kulturarvsdata.se/ksamsok#hasFind',
  'http://kulturarvsdata.se/ksamsok#hasImage',
  'http://kulturarvsdata.se/ksamsok#hasObjectExample',
  'http://kulturarvsdata.se/ksamsok#hasParent',
  'http://kulturarvsdata.se/ksamsok#hasPart',
  'http://kulturarvsdata.se/ksamsok#highresSource',
  'http://kulturarvsdata.se/ksamsok#informant',
  'http://kulturarvsdata.se/ksamsok#intermediary',
  'http://kulturarvsdata.se/ksamsok#interviewer',
  'http://kulturarvsdata.se/ksamsok#inventor',
  'http://kulturarvsdata.se/ksamsok#isDescribedBy',
  'http://kulturarvsdata.se/ksamsok#isFoundIn',
  'http://kulturarvsdata.se/ksamsok#isMentionedBy',
  'http://kulturarvsdata.se/ksamsok#isPartOf',
  'http://kulturarvsdata.se/ksamsok#isRelatedTo',
  'http://kulturarvsdata.se/ksamsok#isVisualizedBy',
  'http://kulturarvsdata.se/ksamsok#itemClass',
  'http://kulturarvsdata.se/ksamsok#itemClassName',
  'http://kulturarvsdata.se/ksamsok#itemColor',
  'http://kulturarvsdata.se/ksamsok#itemForIndexing',
  'http://kulturarvsdata.se/ksamsok#itemKeyWord',
  'http://kulturarvsdata.se/ksamsok#itemLabel',
  'http://kulturarvsdata.se/ksamsok#itemLicenseUrl',
  'http://kulturarvsdata.se/ksamsok#itemMotiveWord',
  'http://kulturarvsdata.se/ksamsok#itemStyle',
  'http://kulturarvsdata.se/ksamsok#itemTechnique',
  'http://kulturarvsdata.se/ksamsok#itemTitle',
  'http://kulturarvsdata.se/ksamsok#iventoryTaker',
  'http://kulturarvsdata.se/ksamsok#ksamsokVersion',
  'http://kulturarvsdata.se/ksamsok#lastChangedDate',
  'http://kulturarvsdata.se/ksamsok#link',
  'http://kulturarvsdata.se/ksamsok#lowresSource',
  'http://kulturarvsdata.se/ksamsok#mason',
  'http://kulturarvsdata.se/ksamsok#masterBuilder',
  'http://kulturarvsdata.se/ksamsok#material',
  'http://kulturarvsdata.se/ksamsok#mediaLicenseUrl',
  'http://kulturarvsdata.se/ksamsok#mediaMotiveWord',
  'http://kulturarvsdata.se/ksamsok#mediaType',
  'http://kulturarvsdata.se/ksamsok#mentions',
  'http://kulturarvsdata.se/ksamsok#mintmaster',
  'http://kulturarvsdata.se/ksamsok#municipalityName',
  'http://kulturarvsdata.se/ksamsok#museumdatUrl',
  'http://kulturarvsdata.se/ksamsok#musician',
  'http://kulturarvsdata.se/ksamsok#name',
  'http://kulturarvsdata.se/ksamsok#nameAuth',
  'http://kulturarvsdata.se/ksamsok#nameId',
  'http://kulturarvsdata.se/ksamsok#number',
  'http://kulturarvsdata.se/ksamsok#surname',
  'http://kulturarvsdata.se/ksamsok#title',
  'http://kulturarvsdata.se/ksamsok#organizer',
  'http://kulturarvsdata.se/ksamsok#painter',
  'http://kulturarvsdata.se/ksamsok#parishName',
  'http://kulturarvsdata.se/ksamsok#patentHolder',
  'http://kulturarvsdata.se/ksamsok#periodAuth',
  'http://kulturarvsdata.se/ksamsok#photographer',
  'http://kulturarvsdata.se/ksamsok#pictureEditor',
  'http://kulturarvsdata.se/ksamsok#placeName',
  'http://kulturarvsdata.se/ksamsok#placeTermAuth',
  'http://kulturarvsdata.se/ksamsok#placeTermId',
  'http://kulturarvsdata.se/ksamsok#presentation',
  'http://kulturarvsdata.se/ksamsok#printer',
  'http://kulturarvsdata.se/ksamsok#producer',
  'http://kulturarvsdata.se/ksamsok#provinceName',
  'http://kulturarvsdata.se/ksamsok#publicist',
  'http://kulturarvsdata.se/ksamsok#publisher',
  'http://kulturarvsdata.se/ksamsok#qualifier',
  'http://kulturarvsdata.se/ksamsok#reseller',
  'http://kulturarvsdata.se/ksamsok#scannerOperator',
  'http://kulturarvsdata.se/ksamsok#scenographer',
  'http://kulturarvsdata.se/ksamsok#seller',
  'http://kulturarvsdata.se/ksamsok#serviceName',
  'http://kulturarvsdata.se/ksamsok#serviceOrganization',
  'http://kulturarvsdata.se/ksamsok#signer',
  'http://kulturarvsdata.se/ksamsok#spec',
  'http://kulturarvsdata.se/ksamsok#technician',
  'http://kulturarvsdata.se/ksamsok#thumbnail',
  'http://kulturarvsdata.se/ksamsok#thumbnailSource',
  'http://kulturarvsdata.se/ksamsok#timeText',
  'http://kulturarvsdata.se/ksamsok#toPeriodId',
  'http://kulturarvsdata.se/ksamsok#toPeriodName',
  'http://kulturarvsdata.se/ksamsok#toTime',
  'http://kulturarvsdata.se/ksamsok#type',
  'http://kulturarvsdata.se/ksamsok#unit',
  'http://kulturarvsdata.se/ksamsok#url',
  'http://kulturarvsdata.se/ksamsok#user',
  'http://kulturarvsdata.se/ksamsok#value',
  'http://kulturarvsdata.se/ksamsok#visualizes',
  'http://kulturarvsdata.se/ksamsok#context',
  'http://kulturarvsdata.se/ksamsok#contextSuperType',
  'http://kulturarvsdata.se/ksamsok#contextType',
  'http://kulturarvsdata.se/ksamsok#continent',
  'http://kulturarvsdata.se/ksamsok#country',
  'http://kulturarvsdata.se/ksamsok#dataQuality',
  'http://kulturarvsdata.se/ksamsok#image',
  'http://kulturarvsdata.se/ksamsok#media',
  'http://kulturarvsdata.se/ksamsok#itemDescription',
  'http://kulturarvsdata.se/ksamsok#itemLicense',
  'http://kulturarvsdata.se/ksamsok#itemMaterial',
  'http://kulturarvsdata.se/ksamsok#itemMeasurement',
  'http://kulturarvsdata.se/ksamsok#itemName',
  'http://kulturarvsdata.se/ksamsok#itemNumber',
  'http://kulturarvsdata.se/ksamsok#itemSpecification',
  'http://kulturarvsdata.se/ksamsok#itemSuperType',
  'http://kulturarvsdata.se/ksamsok#itemType',
  'http://kulturarvsdata.se/ksamsok#mediaLicense',
  'http://kulturarvsdata.se/ksamsok#subject',
  'http://kulturarvsdata.se/ksamsok#theme',
];

const customPropertyCompleter = function(yasqe) {
  let completer = {
    isValidCompletionPosition: () => YASQE.Autocompleters.properties.isValidCompletionPosition(yasqe),
    preProcessToken: (token) => YASQE.Autocompleters.properties.preProcessToken(yasqe, token),
    postProcessToken: (token, suggestedString) => YASQE.Autocompleters.properties.postProcessToken(yasqe, token, suggestedString),
  };

  completer.bulk = true;
  completer.async = false;
  completer.autoShow = true;

  completer.persistent = false;
  completer.get = () => properties;

  return completer;
};

YASQE.registerAutocompleter('customPropertyCompleter', customPropertyCompleter);
